#!/bin/sh

myip=$(ifconfig eth0 | grep "inet " | sed 's/  */ /g' | cut -d' ' -f3)
iprange="$(echo $myip | sed 's/\.[0-9]*$/\.\*/g')"
nmap -sn $iprange | grep -Eo '([0-9][0-9.]+$)' | grep -v "$(echo $myip | sed 's/\./\\\./g')" > hostiplist
for i in $(<hostiplist); do ssh $i hostname; done > hostlist

